/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.learn;

public class App {
    public String getGreeting() {
        return "Shared Library!!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}